[package]
name = "rpi-simon-says"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.2.1"
crossbeam = "0.8.1"
rand = "0.8.4"
rppal = "0.13.1"
rust_gpiozero = { git = "https://github.com/rahul-thakoor/rust_gpiozero" }